version: "3.4"
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    entrypoint: /bin/sh
    ports:
      - 4000:4000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 5100:5100
    environment:
      - NODE_ENV=development
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
    working_dir: /usr/src/app
    command: npm start